### ISSUE TITLE
Add Dockerfiles for each application step

### ISSUE THREAD

**Issue by susheel** [inab/Wetlab2Variations#1]
@scapella Please add the Dockerfiles following applications into the `/containers` folder for reproducibility.

- [ ] cutadapt (v.1.18) --> `/containers/cutadapt/v.1.18/Dockerfile`
- [ ] bwa-mem (v.0.7.17) --> `/containers/bwa-mem/v.0.7.17/Dockerfile`
- [ ] Sambamba (v.0.6.8 ) --> `/containers/Sambamba/v.0.6.8/Dockerfile`
- [ ] Picard (v.2.18.25) --> `/containers/Picard/v.2.18.25/Dockerfile`
- [ ] GATK (v.3.6-0) --> `/containers/GATK/v.3.6-0/Dockerfile`
- [ ] fastqc (v.0.11.8) --> `/containers/fastqc/v.0.11.8/Dockerfile`

Please cross-ref the original Dockerfile if available.

**Comment by rtonda** [comment]
We added our version in the containers folder
