### ISSUE TITLE
Add Nextflow Process descriptions for application steps

### ISSUE THREAD

**Issue by susheel** [inab/Wetlab2Variations#4]
PLease add the process descriptions in Nextflow --> `/nextflow`
- [ ] cutadapt (v.1.18)
- [ ] bwa-mem (v.0.7.17)
- [ ] Sambamba (v.0.6.8)
- [ ] Picard (v.2.18.25)
- [ ] GATK (v.3.6-0)
- [ ] fastqc (v.0.11.8)

**Comment by rtonda** [comment]
We added our version in the containers folder

**Comment by jmfernandez** [comment]
Merged pull request #14 should fulfill this issue
